version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "4000:4000"
    depends_on: 
      - mongodb
  
  mongodb:
    image: "mongo"
    container_name: mongo_db
    ports: 
      - "27017:27017"
    restart: unless-stopped
    volumes: 
      - ./data:/usr/src/app/data/db